package main

import (
	"github.com/caddyserver/caddy/caddy/caddymain"
	// plug in plugins here
	_ "github.com/captncraig/caddy-realip"
	_ "github.com/epicagency/caddy-expires"
	_ "github.com/captncraig/cors"
	_ "github.com/nicolasazrak/caddy-cache"
	_ "github.com/miekg/caddy-prometheus"
	_ "github.com/pyed/ipfilter"
	_ "github.com/xuqingfeng/caddy-rate-limit"
	_ "github.com/captncraig/caddy-realip"
	_ "github.com/epicagency/caddy-expires"
	_ "github.com/captncraig/cors"
	_ "github.com/nicolasazrak/caddy-cache"
	_ "github.com/miekg/caddy-prometheus"
	_ "github.com/pyed/ipfilter"
	_ "github.com/xuqingfeng/caddy-rate-limit"
	_ "github.com/captncraig/caddy-realip"
	_ "github.com/epicagency/caddy-expires"
	_ "github.com/captncraig/cors"
	_ "github.com/nicolasazrak/caddy-cache"
	_ "github.com/miekg/caddy-prometheus"
	_ "github.com/pyed/ipfilter"
	_ "github.com/xuqingfeng/caddy-rate-limit"
	_ "github.com/captncraig/caddy-realip"
	_ "github.com/epicagency/caddy-expires"
	_ "github.com/captncraig/cors"
	_ "github.com/nicolasazrak/caddy-cache"
	_ "github.com/miekg/caddy-prometheus"
	_ "github.com/pyed/ipfilter"
	_ "github.com/xuqingfeng/caddy-rate-limit"
	_ "github.com/captncraig/caddy-realip"
	_ "github.com/epicagency/caddy-expires"
	_ "github.com/captncraig/cors"
	_ "github.com/nicolasazrak/caddy-cache"
	_ "github.com/miekg/caddy-prometheus"
	_ "github.com/pyed/ipfilter"
	_ "github.com/xuqingfeng/caddy-rate-limit"
	_ "github.com/captncraig/caddy-realip"
	_ "github.com/epicagency/caddy-expires"
	_ "github.com/captncraig/cors"
	_ "github.com/nicolasazrak/caddy-cache"
	_ "github.com/miekg/caddy-prometheus"
	_ "github.com/pyed/ipfilter"
	_ "github.com/xuqingfeng/caddy-rate-limit"
	_ "github.com/miekg/caddy-prometheus"
	_ "github.com/pyed/ipfilter"
	_ "github.com/xuqingfeng/caddy-rate-limit"
	_ "github.com/miekg/caddy-prometheus"
	_ "github.com/pyed/ipfilter"
	_ "github.com/xuqingfeng/caddy-rate-limit"
)

func main() {
	caddymain.EnableTelemetry = false
	caddymain.Run()
}
